// src/types/index.ts - Tipos completos del proyecto
import { Timestamp } from 'firebase/firestore'

// ================= BASIC TYPES =================
export type ProductType = 'BA' | 'Aviva_Contigo' | 'Casa_Marchand' | 'Construrama' | 'Disensa'

export type UserRole = 'super_admin' | 'admin' | 'supervisor' | 'promotor'

export type CheckInType = 'entrada' | 'comida' | 'regreso_comida' | 'salida'

export type CheckInStatus = 'a_tiempo' | 'retrasado' | 'anticipado' | 'ubicacion_invalida' | 'auto_closed'

export type TimeOffType = 'vacaciones' | 'aviva_day' | 'incapacidad'

export type RequestStatus = 'pending' | 'approved' | 'rejected'

// ================= HUB TYPES (NUEVO) =================
export interface Hub {
  id: string
  name: string
  description?: string
  states: string[] // Estados geográficos (ej: ["Nuevo León", "Tamaulipas"])
  productTypes: ProductType[] // Productos asignados al hub
  status: 'active' | 'inactive'
  createdAt: Timestamp
  updatedAt: Timestamp
  createdBy: string
  updatedBy?: string
}

// ================= KIOSK TYPES =================
export interface Kiosk {
  id: string
  name: string
  city: string
  state: string
  productType: ProductType
  coordinates: {
    latitude: number
    longitude: number
  }
  radiusOverride?: number // Override del radio por defecto (en metros)
  status: 'active' | 'inactive'
  hubId?: string // NUEVO: Referencia al hub asignado
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= USER TYPES =================
export interface User {
  id: string
  email: string
  name: string
  role: UserRole
  team?: string
  slackId?: string
  status: 'active' | 'inactive'
  assignedKiosk?: string
  assignedKioskName?: string
  productType?: ProductType
  hubId?: string // NUEVO: Referencia al hub asignado
  supervisorId?: string // NUEVO: ID del supervisor asignado
  supervisorName?: string // NUEVO: Nombre del supervisor
  totalLateMinutes?: number // NUEVO: Total de minutos acumulados de retraso
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= CHECK-IN TYPES =================
export interface CheckIn {
  id: string
  userId: string
  userName: string
  kioskId: string
  kioskName: string
  productType: ProductType
  type: CheckInType
  timestamp: Timestamp
  location?: {
    latitude: number
    longitude: number
    accuracy?: number
  }
  photoUrl?: string
  status: CheckInStatus
  notes?: string
  isAutoGenerated?: boolean
  requiresComment?: boolean // NUEVO: Indica si requiere comentario obligatorio
  actionsTaken?: PunctualityAction[] // NUEVO: Acciones ejecutadas por el motor
  validationResults?: {
    locationValid: boolean
    distanceFromKiosk: number
    isOnTime: boolean
    minutesLate: number
    minutesEarly: number
    status: CheckInStatus
  }
  ocrResults?: OCRResult // NUEVO: Resultados del OCR del reloj checador
  createdAt: Timestamp
}

// ================= OCR TYPES =================
export interface OCRResult {
  extractedText: string        // Texto completo extraído por OCR
  clockTime: string | null     // Hora detectada en formato HH:MM
  confidence: number           // Confianza del OCR (0-1)
  serverTime: string           // Hora del servidor cuando se procesó
  timeDifference: number | null // Diferencia en minutos (positivo = reloj adelantado)
  processingTime: number       // Tiempo de procesamiento en ms
  error?: string               // Mensaje de error si falló el OCR
}

export interface CheckInFormData {
  kioskId: string
  kioskName: string
  productType: ProductType
  type: CheckInType
  notes?: string
}

export interface CheckInFilters {
  userId?: string
  kioskId?: string
  productType?: ProductType
  type?: CheckInType
  status?: CheckInStatus
  startDate?: Date
  endDate?: Date
  hubId?: string // NUEVO: Filtrar por hub
}

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ================= SCHEDULE TYPES =================
export interface ProductSchedule {
  id: string
  productType: ProductType
  workDays: number[] // 0=Sunday, 1=Monday, etc.
  schedule: {
    entryTime: string // "08:00"
    exitTime: string  // "18:00"
    lunchStartTime: string // "14:00"
    lunchDuration: number // minutes (60)
  }
  toleranceMinutes: number
  worksOnHolidays: boolean
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= ATTENDANCE TYPES =================
export interface AttendanceIssue {
  id: string
  userId: string
  userName: string
  kioskId?: string
  kioskName?: string
  productType: ProductType
  type:
    | 'no_entry'
    | 'no_exit'
    | 'no_lunch_return'
  expectedTime: string
  detectedAt: Timestamp
  date: Timestamp
  resolved: boolean
  resolvedBy?: string
  resolvedAt?: Timestamp
  resolution?: string
  ruleTriggered?: string   // Qué regla específica se activó
  minutesLate?: number     // Minutos después del límite
}

export interface AttendanceStats {
  totalExpected: number
  totalPresent: number
  totalAbsent: number
  totalLate: number
  totalEarly: number
  attendanceRate: number
  punctualityRate: number
}

// ================= SYSTEM CONFIG =================
export interface SystemConfig {
  toleranceMinutes: number
  severeDelayThreshold: number
  defaultRadius: number
  restDay: string

  absenceRules?: {
    noEntryAfterMinutes: number    // Default: 60
    noExitAfterMinutes: number     // Default: 120
  }

  autoCloseRules?: {
    closeAfterMinutes: number      // Default: 60
    markAsAbsent: boolean          // Default: true
  }

  lunchRules?: {
    maxDurationMinutes: number     // Default: 90
  }

  notificationRules?: {
    notifyOnAbsence: boolean       // Default: true
    notifyOnLateExit: boolean      // Default: false
    notifyOnLateArrival: boolean   // NUEVO: Default: true
    notifyOnLongLunch: boolean     // NUEVO: Default: true
    notifySupervisor: boolean      // NUEVO: Default: true
    notifyAdmin: boolean           // NUEVO: Default: true
    notifyUser: boolean            // NUEVO: Default: true
  }

  alertRules?: {
    generateOnIrregularities: boolean // Default: true
  }

  approvalRules?: {
    requireForLateExit: boolean    // Default: false
  }

  commentRules?: {
    requireOnLateArrival: boolean      // NUEVO: Default: true
    requireOnEarlyDeparture: boolean   // NUEVO: Default: true
    requireOnLongLunch: boolean        // NUEVO: Default: true
    minCommentLength: number           // NUEVO: Default: 10
  }

  slackConfig?: {
    enabled: boolean                   // NUEVO: Default: false
    webhookUrl?: string                // NUEVO: Slack webhook URL
    defaultChannel?: string            // NUEVO: Canal por defecto
    notifyOnLateArrival: boolean      // NUEVO: Default: true
    notifyOnAbsence: boolean          // NUEVO: Default: true
    notifyOnLongLunch: boolean        // NUEVO: Default: true
  }

  updatedAt: Timestamp
  updatedBy: string
}

// ================= TIME OFF TYPES =================
export interface TimeOffRequest {
  id: string
  userId: string
  userName: string
  type: TimeOffType
  startDate: Timestamp
  endDate: Timestamp
  reason: string
  status: RequestStatus
  reviewedBy?: string
  reviewedAt?: Timestamp
  reviewNotes?: string
  createdAt: Timestamp
  updatedAt: Timestamp
}

export interface TimeOffFormData {
  type: TimeOffType
  startDate: Date
  endDate: Date
  reason: string
}

export interface TimeOffFilters {
  userId?: string
  type?: TimeOffType
  status?: RequestStatus
  startDate?: Date
  endDate?: Date
}

// ================= HOLIDAY TYPES =================
export interface Holiday {
  id: string
  name: string
  date: Timestamp
  productTypes?: ProductType[] // Si no se especifica, aplica a todos
  createdAt: Timestamp
}

// ================= NOTIFICATION TYPES =================
export type NotificationType =
  | 'absence_alert'
  | 'time_off_approved'
  | 'time_off_rejected'
  | 'system_alert'
  | 'late_arrival'
  | 'early_departure'
  | 'long_lunch'
  | 'location_violation'

export interface Notification {
  id: string
  type: NotificationType
  title: string
  message: string
  userId?: string
  issueId?: string
  checkInId?: string
  recipientIds?: string[] // NUEVO: IDs de usuarios que deben recibir la notificación
  sentViaSlack?: boolean // NUEVO: Si se envió vía Slack
  slackMessageId?: string // NUEVO: ID del mensaje en Slack
  read: boolean
  createdAt: Timestamp
}

// ================= PUNCTUALITY ACTION ENGINE TYPES =================
export type PunctualityActionType =
  | 'assign_status'           // Asignar estado de puntualidad
  | 'add_late_minutes'        // Sumar minutos de retraso
  | 'require_comment'         // Exigir comentario
  | 'notify_user'            // Notificar al usuario
  | 'notify_supervisor'      // Notificar al supervisor
  | 'notify_admin'           // Notificar a administradores
  | 'notify_slack'           // Notificar vía Slack
  | 'create_issue'           // Crear issue de asistencia

export interface PunctualityAction {
  type: PunctualityActionType
  executedAt: Timestamp
  success: boolean
  error?: string
  details?: {
    statusAssigned?: CheckInStatus
    minutesAdded?: number
    commentRequired?: boolean
    notificationId?: string
    slackMessageId?: string
    issueId?: string
  }
}

export interface PunctualityActionResult {
  checkInId: string
  userId: string
  actions: PunctualityAction[]
  totalActionsExecuted: number
  totalSuccessful: number
  totalFailed: number
  errors?: string[]
}

export interface SlackNotification {
  channel?: string
  username?: string
  icon_emoji?: string
  text: string
  blocks?: Array<{
    type: string
    text?: {
      type: string
      text: string
      emoji?: boolean
    }
    fields?: Array<{
      type: string
      text: string
    }>
    accessory?: {
      type: string
      text?: {
        type: string
        text: string
      }
      url?: string
    }
  }>
  attachments?: Array<{
    color?: string
    blocks?: Array<{
      type: string
      text?: {
        type: string
        text: string
      }
      fields?: Array<{
        type: string
        text: string
      }>
    }>
  }>
}

// ================= DASHBOARD TYPES =================
export interface DashboardStats {
  todayPresent: number
  todayAbsent: number
  todayLate: number
  weeklyTrend: Array<{
    date: string
    present: number
    absent: number
  }>
}

export interface DepartmentStats {
  department: ProductType
  employees: number
  present: number
  absent: number
  attendance: number
  punctuality: number
}
