// src/types/index.ts - Tipos completos del proyecto
import { Timestamp } from 'firebase/firestore'

// ================= BASIC TYPES =================
export type ProductType = 'BA' | 'Aviva_Contigo' | 'Casa_Marchand' | 'Construrama' | 'Disensa'

export type UserRole = 'super_admin' | 'admin' | 'supervisor' | 'promotor'

export type CheckInType = 'entrada' | 'comida' | 'regreso_comida' | 'salida'

export type CheckInStatus = 'a_tiempo' | 'retrasado' | 'anticipado' | 'ubicacion_invalida' | 'auto_closed'

export type TimeOffType = 'vacaciones' | 'aviva_day' | 'incapacidad'

export type RequestStatus = 'pending' | 'approved' | 'rejected'

// ================= HUB TYPES (NUEVO) =================
export interface Hub {
  id: string
  name: string
  description?: string
  states: string[] // Estados geográficos (ej: ["Nuevo León", "Tamaulipas"])
  productTypes: ProductType[] // Productos asignados al hub
  status: 'active' | 'inactive'
  createdAt: Timestamp
  updatedAt: Timestamp
  createdBy: string
  updatedBy?: string
}

// ================= KIOSK TYPES =================
export interface Kiosk {
  id: string
  name: string
  city: string
  state: string
  productType: ProductType
  coordinates: {
    latitude: number
    longitude: number
  }
  radiusOverride?: number // Override del radio por defecto (en metros)
  status: 'active' | 'inactive'
  hubId?: string // NUEVO: Referencia al hub asignado
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= USER TYPES =================
export interface User {
  id: string
  email: string
  name: string
  role: UserRole
  team?: string
  slackId?: string
  status: 'active' | 'inactive'
  assignedKiosk?: string
  assignedKioskName?: string
  productType?: ProductType
  hubId?: string // NUEVO: Referencia al hub asignado
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= CHECK-IN TYPES =================
export interface CheckIn {
  id: string
  userId: string
  userName: string
  kioskId: string
  kioskName: string
  productType: ProductType
  type: CheckInType
  timestamp: Timestamp
  location?: {
    latitude: number
    longitude: number
    accuracy?: number
  }
  photoUrl?: string
  status: CheckInStatus
  notes?: string
  isAutoGenerated?: boolean
  validationResults?: {
    locationValid: boolean
    distanceFromKiosk: number
    isOnTime: boolean
    minutesLate: number
    minutesEarly: number
    status: CheckInStatus
  }
  createdAt: Timestamp
}

export interface CheckInFormData {
  kioskId: string
  kioskName: string
  productType: ProductType
  type: CheckInType
  notes?: string
}

export interface CheckInFilters {
  userId?: string
  kioskId?: string
  productType?: ProductType
  type?: CheckInType
  status?: CheckInStatus
  startDate?: Date
  endDate?: Date
  hubId?: string // NUEVO: Filtrar por hub
}

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ================= SCHEDULE TYPES =================
export interface ProductSchedule {
  id: string
  productType: ProductType
  workDays: number[] // 0=Sunday, 1=Monday, etc.
  schedule: {
    entryTime: string // "08:00"
    exitTime: string  // "18:00"
    lunchStartTime: string // "14:00"
    lunchDuration: number // minutes (60)
  }
  toleranceMinutes: number
  worksOnHolidays: boolean
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ================= ATTENDANCE TYPES =================
export interface AttendanceIssue {
  id: string
  userId: string
  userName: string
  kioskId?: string
  kioskName?: string
  productType: ProductType
  type:
    | 'no_entry'
    | 'no_exit'
    | 'no_lunch_return'
    | 'late_lunch_return'
    | 'auto_closed'
  expectedTime: string
  detectedAt: Timestamp
  date: Timestamp
  resolved: boolean
  resolvedBy?: string
  resolvedAt?: Timestamp
  resolution?: string
  ruleTriggered?: string   // Qué regla específica se activó
  minutesLate?: number     // Minutos después del límite
}

export interface AttendanceStats {
  totalExpected: number
  totalPresent: number
  totalAbsent: number
  totalLate: number
  totalEarly: number
  attendanceRate: number
  punctualityRate: number
}

// ================= SYSTEM CONFIG =================
export interface SystemConfig {
  toleranceMinutes: number
  severeDelayThreshold: number
  defaultRadius: number
  restDay: string

  absenceRules?: {
    noEntryAfterMinutes: number    // Default: 60
    noExitAfterMinutes: number     // Default: 120
  }

  autoCloseRules?: {
    closeAfterMinutes: number      // Default: 60
    markAsAbsent: boolean          // Default: true
  }

  lunchRules?: {
    maxDurationMinutes: number     // Default: 90
  }

  notificationRules?: {
    notifyOnAbsence: boolean       // Default: true
    notifyOnLateExit: boolean      // Default: false
  }

  alertRules?: {
    generateOnIrregularities: boolean // Default: true
  }

  approvalRules?: {
    requireForLateExit: boolean    // Default: false
  }

  updatedAt: Timestamp
  updatedBy: string
}

// ================= TIME OFF TYPES =================
export interface TimeOffRequest {
  id: string
  userId: string
  userName: string
  type: TimeOffType
  startDate: Timestamp
  endDate: Timestamp
  reason: string
  status: RequestStatus
  reviewedBy?: string
  reviewedAt?: Timestamp
  reviewNotes?: string
  createdAt: Timestamp
  updatedAt: Timestamp
}

export interface TimeOffFormData {
  type: TimeOffType
  startDate: Date
  endDate: Date
  reason: string
}

export interface TimeOffFilters {
  userId?: string
  type?: TimeOffType
  status?: RequestStatus
  startDate?: Date
  endDate?: Date
}

// ================= HOLIDAY TYPES =================
export interface Holiday {
  id: string
  name: string
  date: Timestamp
  productTypes?: ProductType[] // Si no se especifica, aplica a todos
  createdAt: Timestamp
}

// ================= NOTIFICATION TYPES =================
export interface Notification {
  id: string
  type: 'absence_alert' | 'time_off_approved' | 'time_off_rejected' | 'system_alert'
  title: string
  message: string
  userId?: string
  issueId?: string
  read: boolean
  createdAt: Timestamp
}

// ================= DASHBOARD TYPES =================
export interface DashboardStats {
  todayPresent: number
  todayAbsent: number
  todayLate: number
  weeklyTrend: Array<{
    date: string
    present: number
    absent: number
  }>
}

export interface DepartmentStats {
  department: ProductType
  employees: number
  present: number
  absent: number
  attendance: number
  punctuality: number
}
